api_v1/urls.py
from django.urls import path, include

from api_v1.views import get_csrf_token_view, add_view, subtract_view, multiply_view, divide_view

app_name = "api_v1"

calculation_urlpatterns = [
    path('add/', add_view, name='add'),
    path('subtract/', subtract_view, name='subtract'),
    path('multiply/', multiply_view, name='multiply'),
    path('divide/', divide_view, name='divide'),
]

urlpatterns = [
    path('get-csrf-token/', get_csrf_token_view),
    path('', include(calculation_urlpatterns))

]

homework69/urls.py
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(api_urlpatterns)),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path

from webapp.views import index_view

urlpatterns = [
    path('', index_view),
]

webapp/models.py
from django.db import models

# Create your models here.

api_v1/views.py
import json

from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse

from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def get_csrf_token_view(request):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed('only GET requests are allowed!')


def add_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        if isinstance(data['A'], int) and isinstance(data['B'], int):
            response = {'answer': data['A'] + data['B']}
            return JsonResponse(response)
        else:
            response = {'error': 'Please enter integer numbers!'}
            return JsonResponse(response, status=400)
    return HttpResponseNotAllowed('only POST requests are allowed!')


def subtract_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        if isinstance(data['A'], int) and isinstance(data['B'], int):
            response = {'answer': data['A'] - data['B']}
            return JsonResponse(response)
        else:
            response = {'error': 'Please enter integer numbers!'}
            return JsonResponse(response, status=400)
    return HttpResponseNotAllowed('only POST requests are allowed!')


def multiply_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        if isinstance(data['A'], int) and isinstance(data['B'], int):
            response = {'answer': data['A'] * data['B']}
            return JsonResponse(response)
        else:
            response = {'error': 'Please enter integer numbers!'}
            return JsonResponse(response, status=400)
    return HttpResponseNotAllowed('only POST requests are allowed!')


def divide_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        if isinstance(data['A'], int) and isinstance(data['B'], int):
            try:
                response = {'answer': data['A'] / data['B']}
            except ZeroDivisionError:
                response = {'error': 'Division by zero!'}
                return JsonResponse(response, status=400)
            return JsonResponse(response)
        else:
            response = {'error': 'Please enter integer numbers!'}
            return JsonResponse(response, status=400)
    return HttpResponseNotAllowed('only POST requests are allowed!')

webapp/views.py
from django.shortcuts import render


def index_view(request):
    return render(request, 'index.html')

webapp/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Calculate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<div class="container mt-3">
    <h1>Enter two numbers and choose one of the operations</h1>
    <div class="row g-3 align-items-center mt-4">
        <div class="col-auto">
            <label for="A" class="col-form-label">Number A</label>
        </div>
        <div class="col-auto">
            <input type="number" id="A" class="form-control">
        </div>
    </div>
    <div class="row g-3 align-items-center mt-4">
        <div class="col-auto">
            <label for="B" class="col-form-label">Number B</label>
        </div>
        <div class="col-auto">
            <input type="number" id="B" class="form-control">
        </div>
    </div>
    <div class="mt-4">
        <button class="btn btn-primary" data-url="{% url 'api_v1:add' %}">ADD</button>
        <button class="btn btn-success" data-url="{% url 'api_v1:subtract' %}">SUBTRACT</button>
        <button class="btn btn-warning" data-url="{% url 'api_v1:multiply' %}">MULTIPLY</button>
        <button class="btn btn-danger" data-url="{% url 'api_v1:divide' %}">DIVIDE</button>
    </div>
    <div id="alert" class="alert alert-dark mt-4" role="alert">
        Here you will see your result...
    </div>
</div>


<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>